// Code generated by protoc-gen-go.
// source: email.proto
// DO NOT EDIT!

package main

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Email struct {
	Id               *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Date             *uint64 `protobuf:"varint,2,req,name=date" json:"date,omitempty"`
	To               *string `protobuf:"bytes,3,req,name=to" json:"to,omitempty"`
	From             *string `protobuf:"bytes,4,req,name=from" json:"from,omitempty"`
	Subject          *string `protobuf:"bytes,5,req,name=subject" json:"subject,omitempty"`
	Mail             *string `protobuf:"bytes,6,req,name=mail" json:"mail,omitempty"`
	Address          *string `protobuf:"bytes,7,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Email) Reset()         { *this = Email{} }
func (this *Email) String() string { return proto.CompactTextString(this) }
func (*Email) ProtoMessage()       {}

func (this *Email) GetId() uint64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Email) GetDate() uint64 {
	if this != nil && this.Date != nil {
		return *this.Date
	}
	return 0
}

func (this *Email) GetTo() string {
	if this != nil && this.To != nil {
		return *this.To
	}
	return ""
}

func (this *Email) GetFrom() string {
	if this != nil && this.From != nil {
		return *this.From
	}
	return ""
}

func (this *Email) GetSubject() string {
	if this != nil && this.Subject != nil {
		return *this.Subject
	}
	return ""
}

func (this *Email) GetMail() string {
	if this != nil && this.Mail != nil {
		return *this.Mail
	}
	return ""
}

func (this *Email) GetAddress() string {
	if this != nil && this.Address != nil {
		return *this.Address
	}
	return ""
}

func init() {
}
