// Code generated by protoc-gen-go.
// source: email.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Email struct {
	Id               *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Date             *uint64 `protobuf:"varint,2,req,name=date" json:"date,omitempty"`
	To               *string `protobuf:"bytes,3,req,name=to" json:"to,omitempty"`
	From             *string `protobuf:"bytes,4,req,name=from" json:"from,omitempty"`
	Subject          *string `protobuf:"bytes,5,req,name=subject" json:"subject,omitempty"`
	Mail             *string `protobuf:"bytes,6,req,name=mail" json:"mail,omitempty"`
	Address          *string `protobuf:"bytes,7,req,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}

func (m *Email) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Email) GetDate() uint64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

func (m *Email) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func (m *Email) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil && m.Subject != nil {
		return *m.Subject
	}
	return ""
}

func (m *Email) GetMail() string {
	if m != nil && m.Mail != nil {
		return *m.Mail
	}
	return ""
}

func (m *Email) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type EmailId struct {
	Timestamp        *int64  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	EmailId          *uint64 `protobuf:"varint,2,req,name=email_id" json:"email_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EmailId) Reset()         { *m = EmailId{} }
func (m *EmailId) String() string { return proto.CompactTextString(m) }
func (*EmailId) ProtoMessage()    {}

func (m *EmailId) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *EmailId) GetEmailId() uint64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type Encrypted struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Data             []byte `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Encrypted) Reset()         { *m = Encrypted{} }
func (m *Encrypted) String() string { return proto.CompactTextString(m) }
func (*Encrypted) ProtoMessage()    {}

func (m *Encrypted) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Encrypted) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PublicKey struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	N                []byte `protobuf:"bytes,2,req,name=n" json:"n,omitempty"`
	E                *int64 `protobuf:"varint,3,req,name=e" json:"e,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}

func (m *PublicKey) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *PublicKey) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *PublicKey) GetE() int64 {
	if m != nil && m.E != nil {
		return *m.E
	}
	return 0
}

type PrivateKey struct {
	Timestamp        *int64   `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	D                []byte   `protobuf:"bytes,2,req,name=d" json:"d,omitempty"`
	Primes           [][]byte `protobuf:"bytes,3,rep,name=primes" json:"primes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}

func (m *PrivateKey) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *PrivateKey) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *PrivateKey) GetPrimes() [][]byte {
	if m != nil {
		return m.Primes
	}
	return nil
}

func init() {
}
